d_hh <- hh %>% 
  mutate_at(c("IMONTH_S", "IBORN_M"),
            funs(case_when(. == "January" ~ 1,
                           . == "February" ~ 2,
                           . == "March" ~ 3,
                           . == "April" ~ 4,
                           . == "May" ~ 5,
                           . == "June" ~ 6,
                           . == "July" ~ 7,
                           . == "August" ~ 8,
                           . == "September" ~ 9,
                           . == "October" ~ 10,
                           . == "November" ~ 11,
                           . == "December" ~ 12))) %>%
  mutate(bc_cate = case_when(BORN_Y %in% 1908:1909 ~ "1908-1909",
                             BORN_Y %in% 1910:1919 ~ "1910-1919",
                             BORN_Y %in% 1920:1929 ~ "1920-1929",
                             BORN_Y %in% 1930:1939 ~ "1930-1939",
                             BORN_Y %in% 1940:1949 ~ "1940-1949",
                             BORN_Y %in% 1950:1959 ~ "1950-1959",
                             BORN_Y %in% 1960:1969 ~ "1960-1969",
                             BORN_Y %in% 1970:1979 ~ "1970-1979",
                             BORN_Y %in% 1980:1989 ~ "1980-1989",
                             BORN_Y %in% 1990:1999 ~ "1990-1999",
                             BORN_Y %in% 2000:2001 ~ "2000-2001"),
         SEX = ifelse(SEX == "Female", "Women", "Men"),
         int = ((YEAR_S - 1900) * 12) + IMONTH_S,
         birth = ((BORN_Y - 1900) * 12) + IBORN_M,
         age = trunc((int - birth) / 12, 1),
         country = case_when(COUNTRY == "Austria GGS wave1" ~ "Austria",
                             COUNTRY == "Belgium GGS wave1" ~ "Belgium",
                             COUNTRY == "Bulgaria GGS wave1" ~ "Bulgaria",
                             COUNTRY == "Belarus GGS wave 1" ~ "Belarus",
                             COUNTRY == "Canada GSS 2006" ~ "Canada",
                             COUNTRY == "Czech Republic GGS wave 1" ~ "Czechia",
                             COUNTRY == "Estonia GGS wave1" ~ "Estonia",
                             COUNTRY == "France GGS wave1" ~ "France",
                             COUNTRY == "Georgia GGS wave1" ~ "Georgia",
                             COUNTRY %in% c("Germany GGS wave1", "Germany Pairfam") ~ "Germany",
                             COUNTRY == "Hungary GGS wave1" ~ "Hungary",
                             COUNTRY == "Italy GGS wave1" ~ "Italy",
                             COUNTRY == "Lithuania GGS wave1" ~ "Lithuania",
                             COUNTRY %in% c("Netherlands FFS", "Netherlands OG 2013") ~ "Netherlands",
                             COUNTRY == "Norway GGS wave1" ~ "Norway",
                             COUNTRY == "Poland GGS wave1" ~ "Poland",
                             COUNTRY == "Romania GGS wave1" ~ "Romania",
                             COUNTRY == "Russia GGS wave1" ~ "Russia",
                             COUNTRY %in% c("Spain SFS 2006", "Spain SFS 2018") ~ "Spain",
                             COUNTRY == "Sweden GGS wave 1" ~ "Sweden",
                             COUNTRY == "UK BHPS" ~ "The UK",
                             COUNTRY %in% c("USA NSFG 1995", "USA NSFG 2007") ~ "The US",
                             COUNTRY == "Uruguay ENCoR 2015" ~ "Uruguay"),
         child1 = ifelse(KID_1 == "Child of order 1", 1, 0),
         child2 = ifelse(KID_2 == "Child of order 2", 1, 0),
         child3 = ifelse(KID_3 == "Child of order 3", 1, 0),
         child4 = ifelse(KID_4 == "Child of order 4", 1, 0),
         child5 = ifelse(KID_5 == "Child of order 5", 1, 0),
         child6 = ifelse(KID_6 == "Child of order 6", 1, 0),
         child7 = ifelse(KID_7 == "Child of order 7", 1, 0),
         child8 = ifelse(KID_8 == "Child of order 8", 1, 0),
         child9 = ifelse(KID_9 == "Child of order 9", 1, 0),
         child10 = ifelse(KID_10 == "Child of order 10", 1, 0),
         child11 = ifelse(KID_11 == "Child of order 11", 1, 0),
         child12 = ifelse(KID_12 == "Child of order 12", 1, 0),
         child13 = ifelse(KID_13 == "Child of order 13", 1, 0),
         child14 = ifelse(KID_14 == "Child of order 14", 1, 0),
         child15 = ifelse(KID_15 == "Child of order 15", 1, 0),
         child16 = ifelse(KID_16 == "Child of order 16", 1, 0),
         child1 = ifelse(is.na(child1), 0, child1),
         child2 = ifelse(is.na(child2), 0, child2),
         child3 = ifelse(is.na(child3), 0, child3),
         child4 = ifelse(is.na(child4), 0, child4),
         child5 = ifelse(is.na(child5), 0, child5),
         child6 = ifelse(is.na(child6), 0, child6),
         child7 = ifelse(is.na(child7), 0, child7),
         child8 = ifelse(is.na(child8), 0, child8),
         child9 = ifelse(is.na(child9), 0, child9),
         child10 = ifelse(is.na(child10), 0, child10),
         child11 = ifelse(is.na(child11), 0, child11),
         child12 = ifelse(is.na(child12), 0, child12),
         child13 = ifelse(is.na(child13), 0, child13),
         child14 = ifelse(is.na(child14), 0, child14),
         child15 = ifelse(is.na(child15), 0, child15),
         child16 = ifelse(is.na(child16), 0, child16),
         num_child = child1 + child2 + child3 + child4 + child5 + child6 +
           child7 + child8 + child9 + child10 + child11 + child12 + child13 +
           child14 + child15 + child16,
         everbirth = ifelse(num_child > 0, 1, 0),
         union1 = ifelse(UNION_1 == "Union of order 1", 1, 0),
         union2 = ifelse(UNION_2 == "Union of order 2", 1, 0),
         union3 = ifelse(UNION_3 == "Union of order 3", 1, 0),
         union4 = ifelse(UNION_4 == "Union of order 4", 1, 0),
         union5 = ifelse(UNION_5 == "Union of order 5", 1, 0),
         union6 = ifelse(UNION_6 == "Union of order 6", 1, 0),
         union7 = ifelse(UNION_7 == "Union of order 7", 1, 0),
         union8 = ifelse(UNION_8 == "Union of order 8", 1, 0),
         union9 = ifelse(UNION_9 == "Union of order 9", 1, 0),
         union1 = ifelse(is.na(union1), 0, union1),
         union2 = ifelse(is.na(union2), 0, union2),
         union3 = ifelse(is.na(union3), 0, union3),
         union4 = ifelse(is.na(union4), 0, union4),
         union5 = ifelse(is.na(union5), 0, union5),
         union6 = ifelse(is.na(union6), 0, union6),
         union7 = ifelse(is.na(union7), 0, union7),
         union8 = ifelse(is.na(union8), 0, union8),
         union9 = ifelse(is.na(union9), 0, union9),
         num_union = union1 + union2 + union3 + union4 + union5 + union6 +
           union7 + union8 + union9,
         everunion = ifelse(num_union > 0, 1, 0),
         datasetname = "HH",
         RESPID = as.character(RESPID)) %>% 
  select(id = RESPID, country, sex = SEX, age, bc_cate, birthyear = BORN_Y, education = EDU_3, 
         everbirth, everunion, dataset = COUNTRY, datasetname)
saveRDS(d_hh, file = "../../../Users/rymo/OneDrive - Syddansk Universitet/BigData/tempo/d_hh.rds")
